# Generated by Django 5.2.9 on 2026-01-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
